# Generated by Django 3.2.6 on 2021-08-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees', models.BooleanField(default=False, max_length=5)),
                ('quran_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('tajweed_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('nahw_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('sorf_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('uluum_ulquran_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('balaagah_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('tawheed_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('farooid_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('fiqh_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('taareekh_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('hadeeth_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('aruud_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('mantiqoh_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('tafseer_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('mustolah_ulhadeeth_ca', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('quran_exam', models.IntegerField(blank=True, default=0, verbose_name='القرآن (الإمتحان)')),
                ('tajweed_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('nahw_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('sorf_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('uluum_ulquran_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('balaagah_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('tawheed_exam', models.IntegerField(blank=True, default=0, verbose_name='التوحيد (الإمتحان)')),
                ('farooid_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('fiqh_exam', models.IntegerField(blank=True, default=0, verbose_name='الفقه (الإمتحان)')),
                ('taareekh_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('hadeeth_exam', models.IntegerField(blank=True, default=0, verbose_name='الحديث (الإمتحان)')),
                ('aruud_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('mantiqoh_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('tafseer_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('mustolah_ulhadeeth_exam', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('quran_tot', models.IntegerField(blank=True, default=0)),
                ('tajweed_tot', models.IntegerField(blank=True, default=0)),
                ('nahw_tot', models.IntegerField(blank=True, default=0)),
                ('sorf_tot', models.IntegerField(blank=True, default=0)),
                ('uluum_ulquran_tot', models.IntegerField(blank=True, default=0)),
                ('balaagah_tot', models.IntegerField(blank=True, default=0)),
                ('tawheed_tot', models.IntegerField(blank=True, default=0)),
                ('farooid_tot', models.IntegerField(blank=True, default=0)),
                ('fiqh_tot', models.IntegerField(blank=True, default=0)),
                ('taareekh_tot', models.IntegerField(blank=True, default=0)),
                ('hadeeth_tot', models.IntegerField(blank=True, default=0)),
                ('aruud_tot', models.IntegerField(blank=True, default=0)),
                ('mantiqoh_tot', models.IntegerField(blank=True, default=0)),
                ('tafseer_tot', models.IntegerField(blank=True, default=0)),
                ('mustolah_ulhadeeth_tot', models.IntegerField(blank=True, default=0)),
                ('cumulative', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arabiyyah_nursery_pupil', to='records.pupil')),
                ('session', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arabiyyah_nursery_session', to='management.session')),
            ],
            options={
                'verbose_name': 'First Term Score',
                'verbose_name_plural': 'First Term Scores',
                'ordering': ('pupil__user__username',),
            },
        ),
    ]
