# Generated by Django 3.2.6 on 2021-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstterm',
            name='aruud_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='العروض (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='aruud_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='العروض (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='balaagah_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='البلاغة (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='balaagah_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='البلاغة (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='farooid_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='الفرائض (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='farooid_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='الفرائض (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='fiqh_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='الفقه (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='hadeeth_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='الحديث (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='mantiqoh_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='المنطقة (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='mantiqoh_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='المنطقة (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='mustolah_ulhadeeth_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='مصطلح الحديث (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='mustolah_ulhadeeth_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='مصطلح الحديث (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='nahw_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='النحو (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='nahw_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='النحو (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='quran_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='القرآن (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='sorf_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='الصرف (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='sorf_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='الصرف (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='taareekh_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='التاريخ (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='taareekh_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='التاريخ (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='tafseer_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='التفسير (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='tafseer_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='التفسير (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='tajweed_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='التجويد (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='tajweed_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='التجويد (الإمتحان)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='tawheed_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='التوحيد (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='uluum_ulquran_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='علوم القرآن (الإختبار)'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='uluum_ulquran_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='علوم القرآن (الإمتحان)'),
        ),
    ]
