# Generated by Django 3.2.6 on 2021-08-15 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('records', '0001_initial'),
        ('secondary', '0002_auto_20210814_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstterm',
            options={'ordering': ('student__user__username',), 'verbose_name': 'First Term Score', 'verbose_name_plural': 'First Term Scores'},
        ),
        migrations.RemoveField(
            model_name='firstterm',
            name='pupil',
        ),
        migrations.AddField(
            model_name='firstterm',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_student', to='records.student'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='session',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_session', to='management.session'),
        ),
    ]
