# Generated by Django 3.2.6 on 2021-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20210815_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='head_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='teacher_comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
