# Generated by Django 3.2.6 on 2021-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20210815_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstterm',
            name='head_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق المدير'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق المدرس'),
        ),
    ]
