# Generated by Django 3.2.6 on 2021-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
