# Generated by Django 3.2.6 on 2021-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('next', models.DateField(blank=True, null=True, verbose_name='Next Term Begins')),
                ('head', models.CharField(blank=True, max_length=40, null=True, verbose_name="Headmaster's Name")),
                ('school', models.ImageField(blank=True, null=True, upload_to='stamp_img/%Y/%m/%d', verbose_name="School's Stamp with Head of Schools Signature")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
