# Generated by Django 3.2.6 on 2022-05-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20, null=True, verbose_name='Class')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature_img/%Y/%m/%d', verbose_name="Class Teacher's Signature")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ('classe',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('head', models.CharField(blank=True, max_length=40, null=True, verbose_name="Head of School's Name")),
                ('school', models.ImageField(blank=True, null=True, upload_to='stamp_img/%Y/%m/%d', verbose_name="School's Stamp")),
                ('number', models.CharField(blank=True, max_length=7, null=True, verbose_name='No of Days School Opens')),
                ('next', models.DateField(blank=True, null=True, verbose_name='Next Term Begins')),
                ('first_report', models.BooleanField(default=False, max_length=5, verbose_name='Open 1st Term Report')),
                ('second_report', models.BooleanField(default=False, max_length=5, verbose_name='Open 2nd Term Report')),
                ('third_report', models.BooleanField(default=False, max_length=5, verbose_name='Open 3rd Term Report')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=2, null=True, verbose_name='S/N')),
                ('subject', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.class', verbose_name='Class')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
