# Generated by Django 3.2.6 on 2021-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ends',
            field=models.DateField(blank=True, null=True, verbose_name='Term Ends'),
        ),
    ]
