# Generated by Django 3.2.6 on 2022-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=80, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_img/%Y/%m/%d')),
                ('home_page', models.BooleanField(default=False, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News or Event',
                'verbose_name_plural': 'News and Events',
                'ordering': ('-created',),
            },
        ),
    ]
