# Generated by Django 3.2.6 on 2021-08-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_session_ends'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees', models.BooleanField(default=False, max_length=5)),
                ('quran_ca', models.IntegerField(blank=True, default=0, verbose_name='القرآن (الإختبار)')),
                ('tajweed_ca', models.IntegerField(blank=True, default=0, verbose_name='التجويد (الإختبار)')),
                ('mutoolaah_ca', models.IntegerField(blank=True, default=0, verbose_name='المطالعة (الإختبار)')),
                ('arabiyyah_ca', models.IntegerField(blank=True, default=0, verbose_name='العربية (الإختبار)')),
                ('nahw_ca', models.IntegerField(blank=True, default=0, verbose_name='النحو (الإختبار)')),
                ('tawheed_ca', models.IntegerField(blank=True, default=0, verbose_name='التوحيد (الإختبار)')),
                ('fiqh_ca', models.IntegerField(blank=True, default=0, verbose_name='الفقه (الإختبار)')),
                ('seeroh_ca', models.IntegerField(blank=True, default=0, verbose_name='السيرة (الإختبار)')),
                ('hadeeth_ca', models.IntegerField(blank=True, default=0, verbose_name='الحديث (الإختبار)')),
                ('imlaa_ca', models.IntegerField(blank=True, default=0, verbose_name='الإملاء (الإختبار)')),
                ('khot_ca', models.IntegerField(blank=True, default=0, verbose_name='الخط العربي (الإختبار)')),
                ('quran_exam', models.IntegerField(blank=True, default=0, verbose_name='القرآن (الإمتحان)')),
                ('tajweed_exam', models.IntegerField(blank=True, default=0, verbose_name='التجويد (الإمتحان)')),
                ('mutoolaah_exam', models.IntegerField(blank=True, default=0, verbose_name='المطالعة (الإمتحان)')),
                ('arabiyyah_exam', models.IntegerField(blank=True, default=0, verbose_name='العربية (الإمتحان)')),
                ('nahw_exam', models.IntegerField(blank=True, default=0, verbose_name='النحو (الإمتحان)')),
                ('tawheed_exam', models.IntegerField(blank=True, default=0, verbose_name='التوحيد (الإمتحان)')),
                ('fiqh_exam', models.IntegerField(blank=True, default=0, verbose_name='الفقه (الإمتحان)')),
                ('seeroh_exam', models.IntegerField(blank=True, default=0, verbose_name='السيرة (الإمتحان)')),
                ('hadeeth_exam', models.IntegerField(blank=True, default=0, verbose_name='الحديث (الإمتحان)')),
                ('imlaa_exam', models.IntegerField(blank=True, default=0, verbose_name='الإملاء (الإمتحان)')),
                ('khot_exam', models.IntegerField(blank=True, default=0, verbose_name='الخط العربي (الإمتحان)')),
                ('quran_tot', models.IntegerField(blank=True, default=0)),
                ('tajweed_tot', models.IntegerField(blank=True, default=0)),
                ('mutoolaah_tot', models.IntegerField(blank=True, default=0)),
                ('arabiyyah_tot', models.IntegerField(blank=True, default=0)),
                ('nahw_tot', models.IntegerField(blank=True, default=0)),
                ('tawheed_tot', models.IntegerField(blank=True, default=0)),
                ('fiqh_tot', models.IntegerField(blank=True, default=0)),
                ('seeroh_tot', models.IntegerField(blank=True, default=0)),
                ('hadeeth_tot', models.IntegerField(blank=True, default=0)),
                ('imlaa_tot', models.IntegerField(blank=True, default=0)),
                ('khot_tot', models.IntegerField(blank=True, default=0)),
                ('cumulative', models.IntegerField(blank=True, default=0)),
                ('teacher_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق المدرس')),
                ('head_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق المدير')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursery_pupil', to='records.pupil')),
                ('session', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursery_session', to='management.session')),
            ],
            options={
                'verbose_name': 'First Term Score',
                'verbose_name_plural': 'First Term Scores',
                'ordering': ('pupil__user__username',),
            },
        ),
    ]
