# Generated by Django 3.2.6 on 2021-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='duruusu_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='دروس اللغة (الإختبار)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='duruusu_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='دروس اللغة (الإمتحان)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='duruusu_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='hadeethulhifz_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='حديث الحفظ (الإختبار)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='hadeethulhifz_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='حديث الحفظ (الإمتحان)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='hadeethulhifz_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='nusuus_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='النصوص (الإختبار)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='nusuus_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='النصوص (الإمتحان)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='nusuus_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='tabeer_ca',
            field=models.IntegerField(blank=True, default=0, verbose_name='التعبير (الإختبار)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='tabeer_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='التعبير (الإمتحان)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='tabeer_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
